version: "2.17.3"
services:
  web:
    image: nginx
    ports:
      - 9090:9090
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    environment:
      "REDIS_HOST": "redis"

  app2:
    build: .
    environment:
      "REDIS_HOST": "redis"

  app3:
    build: .
    environment:
      "REDIS_HOST": "redis"

  redis:
    image: redis:alpine
    depends_on:
      - app1
      - app2
      - app3